language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - pecl install https://github.com/chobie/php-protocolbuffers/archive/master.zip
  - composer self-update
  - composer install --no-interaction --prefer-source --dev -o

script: php vendor/bin/phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
