language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - ./tests/ci/scripts/install_php_protobuf.sh
  - composer self-update
  - composer install --no-interaction --prefer-source --dev -o

script: php vendor/bin/phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
